// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oracleconnector.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import oracleconnector.impl.JdbcConnector;

public class SetInParameterObject extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String Entity;
	private IMendixObject ObjectValue;
	private java.lang.String SqlType;

	public SetInParameterObject(IContext context, java.lang.String Entity, IMendixObject ObjectValue, java.lang.String SqlType)
	{
		super(context);
		this.Entity = Entity;
		this.ObjectValue = ObjectValue;
		this.SqlType = SqlType;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		connector.setInParameterObject(this.ObjectValue,this.SqlType);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SetInParameterObject";
	}

	// BEGIN EXTRA CODE
	private final ILogNode logNode = Core.getLogger(JdbcConnector.LOGNAME);
	private final JdbcConnector connector = new JdbcConnector(logNode);

	// END EXTRA CODE
}
