// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testoracleconnector.proxies;

public class Users
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject usersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestOracleConnector.Users";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		USERNAME("USERNAME"),
		USERID("USERID"),
		CREATED("CREATED");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Users(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestOracleConnector.Users"));
	}

	protected Users(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject usersMendixObject)
	{
		if (usersMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestOracleConnector.Users", usersMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestOracleConnector.Users");

		this.usersMendixObject = usersMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Users.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testoracleconnector.proxies.Users initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testoracleconnector.proxies.Users.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static testoracleconnector.proxies.Users initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testoracleconnector.proxies.Users(context, mendixObject);
	}

	public static testoracleconnector.proxies.Users load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testoracleconnector.proxies.Users.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of USERNAME
	 */
	public final java.lang.String getUSERNAME()
	{
		return getUSERNAME(getContext());
	}

	/**
	 * @param context
	 * @return value of USERNAME
	 */
	public final java.lang.String getUSERNAME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.USERNAME.toString());
	}

	/**
	 * Set value of USERNAME
	 * @param username
	 */
	public final void setUSERNAME(java.lang.String username)
	{
		setUSERNAME(getContext(), username);
	}

	/**
	 * Set value of USERNAME
	 * @param context
	 * @param username
	 */
	public final void setUSERNAME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.USERNAME.toString(), username);
	}

	/**
	 * @return value of USERID
	 */
	public final java.lang.Long getUSERID()
	{
		return getUSERID(getContext());
	}

	/**
	 * @param context
	 * @return value of USERID
	 */
	public final java.lang.Long getUSERID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.USERID.toString());
	}

	/**
	 * Set value of USERID
	 * @param userid
	 */
	public final void setUSERID(java.lang.Long userid)
	{
		setUSERID(getContext(), userid);
	}

	/**
	 * Set value of USERID
	 * @param context
	 * @param userid
	 */
	public final void setUSERID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long userid)
	{
		getMendixObject().setValue(context, MemberNames.USERID.toString(), userid);
	}

	/**
	 * @return value of CREATED
	 */
	public final java.util.Date getCREATED()
	{
		return getCREATED(getContext());
	}

	/**
	 * @param context
	 * @return value of CREATED
	 */
	public final java.util.Date getCREATED(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CREATED.toString());
	}

	/**
	 * Set value of CREATED
	 * @param created
	 */
	public final void setCREATED(java.util.Date created)
	{
		setCREATED(getContext(), created);
	}

	/**
	 * Set value of CREATED
	 * @param context
	 * @param created
	 */
	public final void setCREATED(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date created)
	{
		getMendixObject().setValue(context, MemberNames.CREATED.toString(), created);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return usersMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testoracleconnector.proxies.Users that = (testoracleconnector.proxies.Users) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestOracleConnector.Users";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
